### ISSUE TITLE
Keine Verbindung zum HomeServer möglich

### ISSUE THREAD

**Issue by nowi967** [metaneutrons/node-red-contrib-gira-rest#1]
Hallo Fabian,

seit Tagen versuche ich dein Node zu konfigurieren.
Heute habe ich es meiner Meinung nach endlich geschafft die Connection zum Host richtig zu konfigurieren ABER leider sind die Abfragen viel zu hoch.
Die Abfragen sind so hoch, dass mein NodeRed die Grätsche macht.

Zusätzlich dazu sind meine Anfragen leer.

Ich hoffe du kannst mir weiter helfen. 
Danke.

![Bildschirmfoto 2021-04-24 um 23 08 36](https://user-images.githubusercontent.com/67169020/115973010-3c26a900-a552-11eb-878d-657d37509a63.png)

![Bildschirmfoto 2021-04-24 um 22 55 06](https://user-images.githubusercontent.com/67169020/115972692-316b1480-a550-11eb-8f38-892b15bdf2ac.png)

![Bildschirmfoto 2021-04-24 um 22 57 46](https://user-images.githubusercontent.com/67169020/115972747-8870e980-a550-11eb-8828-229842ce38fa.png)

**Comment by metaneutrons** [comment]
Moin, als Callback URL musst Du das Wurzelverzeichnis Deiner Node-Red Instanz angeben. Der Callback-Pfad wird automatisch generiert und dem HomeServer übergeben.

Du brauchst daher auch keinen eigenen HTTP-Responder. Den Callback verarbeitet das Plugin selbst (sollte es jedenfalls).

Lösch' also mal das "/girahomeserver" bei der Callback-URL.
